#!/usr/bin/env bash
#sudo pkill -9 -f gunicorn
cd ***ROOT***/
source __defaults__/env/bash
export INTERACTIVE="false"
if [ ! -f "***DATABASE***/data/db.sqlite3" ] ; then
	export MIGRATIONS="true"
	/www-data/venv/bin/python3 ***ROOT***/manage.py migrate
fi
export MIGRATIONS="false"
export WEBSITE_BASE="***WEBSITE_BASE***/"
export GUNICORN="true"
export LIVE="true"
sudo chown -R $USER /www-data
/www-data/venv/bin/gunicorn \
  --timeout 86400 \
  --access-logfile - \
  --workers 1 \
  --bind unix:/www-data/gunicorn.sock \
  __defaults__.django.wsgi:application